/**
 * API Barrel Export
 *
 * All imports should use "@/lib/api" instead of "@/lib/api/client".
 */

export {
  // Types
  type BackendFactSheet,
  type IntakeResponse,
  type VerifyResponse,
  type GenerateResponse,
  type ChatResponse,
  type SensitivityFlag,
  type ComplianceAnalysis,
  type SensitivityReport,
  type SceneCharacterAssignment,
  type CharacterRecommendation,
  type Avatar,
  type ConfigResponse,
  type VideoAssetsStage,
  type ScriptSegment,
  type VeoScript,
  type CharacterDescription,
  type CharacterRefImage,
  type ClipRefEntry,
  type VeoClipEntry,
  type VisualAudioState,
  type VideoAssetsResponse,
  type RecommendAvatarsRequest,
  type RecommendAvatarsResponse,
  type PreviewFrame,
  type RefinementEntry,
  type PreviewState,
  type GeneratePreviewFramesRequest,
  type GeneratePreviewFramesResponse,
  type ChatPreviewFramesRequest,
  type ChatPreviewFramesResponse,
  type ChatCharacterRequest,
  type ChatCharacterResponse,
  type VideoAssetsStatusResponse,
  type FrontendFactCheck,
  type SerperNewsItem,
  type SerperNewsResponse,
  type SocialTrendAnalysis,
  type SocialCaptionOption,
  type SocialThumbnailRecommendation,
  type SocialHashtagStrategy,
  type SocialOutput,
  type SocialGenerateResponse,
  type ChatSocialResponse,
  type FirestoreProject,
  type ProjectsListResponse,

  // Functions
  submitIntake,
  submitIntakeStream,
  verifyFactSheet,
  generateVideoPackage,
  chatFactSheet,
  chatVideoPackage,
  recommendAvatars,
  getAvatars,
  getConfig,
  healthCheck,
  generateVideoAssets,
  getVideoAssetsStatus,
  generatePreviewFrames,
  chatPreviewFrames,
  chatCharacterRefinement,
  fetchTrendingNews,
  generateSocialStrategy,
  chatSocialStrategy,
  getSocialStrategy,
} from "./client";
